# -*- encoding: utf-8 -*-
{
    "name" : "Factura Electrónica Costa Rica",
    "version" : "1.0",
    "author" : "Nagsis",
    "category" : "Accountant",
    "description" : """Factura Electrónica Costa Rica""",
    "depends" : [
        'base',
        'solt_web',
        'medical_l10n_cr_toponyms',
        'account_cancel',
        'account_accountant',
        'product_uos',
        'sale_stock'
    ],
    "data": [
        'security/ir.model.access.csv',
        "security/cr_security_rules.xml",
        "data/billing_doc_template.xml",
        "data/invoice_condition_cr.xml",
        "data/payment_method_cr.xml",
        "data/invoice_product_code_type.xml",
        "data/account_group_data.xml",
        "data/exoneration_type.xml",
        "data/product_unit_data.xml",
        "views/invoice_view.xml",
        "views/partner.xml",
        "views/edi_view.xml",
        "views/company_view.xml",
        "views/ebiller.xml",
        "views/account_tax_group.xml",
        "views/tax_view.xml",
        "views/product_view.xml",
        "views/nature_discount.xml",
        "views/journal.xml",
        "views/invoice_condition.xml",
        "wizard/wizard_message_view.xml",
        "views/document_generic_view.xml",
        "views/menuitems.xml",
    ],
    "installable" : True,
}